### ISSUE TITLE
Pattern "Occupied Slots" ignores items from the offhand

### ISSUE THREAD

**Issue by LevAlTru** [N08I40K/hexecuteif#1]
### The problem:
I have installed Hexecuteif along with Hexal. Hexal has an item called "Mote Hexus" which can store items via media. The problem is i can't use my offhand or my inventory for sending the items to the Mote Hexus, i have to use item entities. So i decided it is not a problem with Hexecuteif because i can drop items from my offhand. But i couldn't because i can't get the slot bumber for the offhand.

### How to reproduce:
1) Play on Forge 1.19.2
2) Take a staff for casting the spells take any item to the offhand
3) cast the following:
![image](https://github.com/N08I40K/hexecuteif/assets/68346194/8226c339-098b-42bf-b5dd-bfd90592d697)
4) spot incorrect data in the stack
![image](https://github.com/N08I40K/hexecuteif/assets/68346194/01052a29-75bd-4b75-bef8-b4c11bf9866b)
![image](https://github.com/N08I40K/hexecuteif/assets/68346194/7a3484d7-fdbf-4da7-b874-f77a6d85dcb1)

### Additional information:
This bug might be because of minecraft showing the offhand slot as a negative number
To check it use command "/data get entity @p Inventory"
![image](https://github.com/N08I40K/hexecuteif/assets/68346194/0fb12393-1819-42c9-a593-e91fa7b9605b)

**Comment by n08i40k** [comment]
Hello! I apologize for such a long answer. Spells for working with inventory do not yet support the second hand, armor and mod slots (curious api for forge / trinkets for fabric).

I will add their support in the near future.

**Comment by n08i40k** [comment]
You can now interact with the offhand slot and armor slots.

Slot 36 - Offhand.
Slot 37 - Boot slot.
Etc...

As an example, this spell moves 1 item from the offhand to the first hotbar slot.
![image](https://github.com/N08I40K/hexecuteif/assets/55545594/7d020485-6aeb-44d7-8d38-ee8cc997a599)
